version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:7.4-apache
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    ports:
      - 8000:80
  db:
    platform: linux/x86_64
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: Root123
        MYSQL_DATABASE: exam
        MYSQL_USER: admin
        MYSQL_PASSWORD: Admin123
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db

